language: python

python:
  - "3.6"

services: postgresql

env:
  - TRAVIS=True
  - TRAVIS_KEY='aa6nu-#zjeq()8/*4pefo=%6e7_^m6vyc@93ze-se!ib-$k43%n'
  - DATABASE_NAME='travisci'
  - DATABASE_USER='postgres'
  - DATABASE_PASSWORD=''

before_script:
  - psql -c "CREATE DATABASE travisci;" -U postgres

script:
  - python manage.py migrate
  - python manage.py test
