# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z\\s]', 'Solo letras', 'No valido')]),
        ),
    ]
