# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name': 'Cupones'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Productos'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(upload_to='coupons', verbose_name='Imagen'),
        ),
    ]
