# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 03:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_auto_20180606_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='categories', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z\r]', 'Ingrese solo letras', 'No valido')]),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z\r]', 'Ingrese solo letras', 'No valido')], verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z\r]', 'Ingrese solo letras', 'No valido')], verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator('([A-Za-z\r])\\w+', 'Ingrese solo letras y números', 'No valido')], verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('[a-zA-Z\r]', 'Ingrese solo letras', 'No valido')], verbose_name='Titulo'),
        ),
    ]
