# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 02:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_auto_20180614_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=150, validators=[django.core.validators.RegexValidator('([A-Za-z\r])\\w+', 'Ingrese solo letras y números', 'No valido')], verbose_name='Descripcion'),
        ),
    ]
