# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_auto_20180114_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de fin de Vigencia'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogue.Category', verbose_name='Categoria'),
        ),
    ]
