# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 02:57
from __future__ import unicode_literals

import apps.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20180712_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=30, validators=[apps.catalogue.validators.description_validator], verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=30, validators=[apps.catalogue.validators.description_validator], verbose_name='Titulo'),
        ),
    ]
