# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_auto_20180115_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actuaizado'),
        ),
        migrations.AddField(
            model_name='product',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Publicado'),
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actuaizado'),
        ),
    ]
