# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 00:54
from __future__ import unicode_literals

import apps.catalogue.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0007_auto_20180805_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, max_length=60, validators=[apps.catalogue.validators.description_validator, django.core.validators.MaxLengthValidator(60)], verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, max_length=60, validators=[apps.catalogue.validators.description_validator, django.core.validators.MaxLengthValidator(60)], verbose_name='Descripcion'),
        ),
    ]
