# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 15:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0008_auto_20180117_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='product',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='date_expiry',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Expiracion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Está activo?'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='modified_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por'),
            preserve_default=False,
        ),
    ]
