# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-28 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0010_auto_20180128_0229'),
        ('catalogue', '0011_auto_20180128_2136'),
    ]

    operations = [
    ]
