# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-13 21:29
from __future__ import unicode_literals

import apps.catalogue.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0012_merge_20180128_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Está activo?')),
                ('title', models.CharField(max_length=30, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, max_length=50, verbose_name='Descripcion')),
                ('image', models.ImageField(upload_to='offers', verbose_name='Imagen')),
                ('date_expiry', models.DateTimeField(validators=[apps.catalogue.validators.date_validator], verbose_name='Fecha de Expiracion')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('modified_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_expiry',
            field=models.DateTimeField(validators=[apps.catalogue.validators.date_validator], verbose_name='Fecha de Expiracion'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=50, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titulo'),
        ),
    ]
