# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 00:06
from __future__ import unicode_literals

import apps.catalogue.models
import apps.catalogue.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_auto_20180513_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterField(
            model_name='coupon',
            name='date_expiry',
            field=models.DateTimeField(default=apps.catalogue.models.timestap, validators=[apps.catalogue.validators.date_validator], verbose_name='Fecha de Expiracion'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_expiry',
            field=models.DateTimeField(default=apps.catalogue.models.timestap, validators=[apps.catalogue.validators.date_validator], verbose_name='Fecha de Expiracion'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, max_length=100, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=100, verbose_name='Descripcion'),
        ),
    ]
