# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180514_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='date_expiry',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(upload_to='%(class)s', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='%(class)s', verbose_name='Imagen'),
        ),
    ]
