# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0015_auto_20180516_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='image',
            field=models.ImageField(upload_to='%(class)ss', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='%(class)ss', verbose_name='Imagen'),
        ),
    ]
