# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-03 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Ciudades',
                'verbose_name': 'Ciudad',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_3166_2', models.CharField(blank=True, max_length=3, verbose_name='ISO 3166-2')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
            ],
            options={
                'verbose_name_plural': 'Provincias',
                'verbose_name': 'Provincia',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='address.Province', verbose_name='Provincia'),
        ),
    ]
