# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20180103_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sector',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identification',
            field=models.CharField(blank=True, max_length=13, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Teléfono de trabajo'),
        ),
    ]
