# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 03:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20180604_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='identification',
        ),
    ]
