# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponrecord',
            name='coupon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.Coupon', verbose_name='Cupón'),
        ),
        migrations.AlterField(
            model_name='offerrecord',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.Offer', verbose_name='Oferta'),
        ),
        migrations.AlterField(
            model_name='productrecord',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='catalogue.Product', verbose_name='Producto'),
        ),
    ]
